name: standard
dependencies:
  - python=3.6
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - geopandas
    - shapely
    - folium
    - plotly_express
    - sentinelhub
    - rasterio
    - earthpy
  - conda
  - conda:
    - ipykernel 